import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import { dataInitial } from "@/lib/scriptData";


const league_Spartan = League_Spartan({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Invoice app",
  description: "Generated by create next app",
  icons: "/img/favicon-32x32.png"
};

export  default async  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  await dataInitial()

  return (
    <html lang="en">
      <body className={`${league_Spartan.className} dark:bg-[#141625] bg-[#ffff] `} >
        <main className="w-full dark:text-white flex flex-col items-center">
          <Nav  />
          <div id="body" className="w-full min-h-full  flex justify-center" >
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
